---
title: "Hoe verloopt een sessie met Bach Bloesem Remedies?"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---

In een veilige en rustige omgeving help ik jou om aan te komen bij jezelf. Via gesprekstherapie krijg je de mogelijkheid om je te focussen op je eigen behoeften en die te uiten, waardoor je gemoedstoestanden erkent en moeilijkheden in perspectief kan zetten. Jij bepaalt waar je het over wil hebben. Het is jouw weg en ritme. Zoals het pellen van een ui, laag per laag dichter bij je kern, naar wie je werkelijk bent. De Bach Bloesem Remedies zijn een ondersteuning op die weg. Ik zorg vanop de zijlijn voor de juiste steun en condities.

Tijdens de sessie bespreken we de Bach Bloesems die aan de oppervlakte liggen en selecteren we de samenstelling voor jouw remedieflesje. Ik vind het zeer belangrijk dat je je verhaal kunt doen en inzichten en handvaten krijgt om verder mee op weg te gaan. Tijdens het gesprek krijg je de keuze of ik al dan niet een remedieflesje voor je aanmaak. Je kan de remedies ook vinden in de apotheek of natuurwinkels.