---
title: "Consult"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---

Consultatie met [Fien Morel](./about.html) is enkel mogelijk op afspraak.
Hiervoor kan je telefonisch [contact](./contact.html) met me opnemen: 0486 52 41 56
Tijdens een consult neem ik de telefoon niet op.
Spreek gerust een bericht in en ik bel je zo spoedig mogelijk terug.

Een consult Bach Bloesemtherapie duurt ongeveer één uur en kost € 50 (€ 45 voor het consult en € 5 voor je remedieflesje).
Bij een kort consult of een consult dat langer duurt dan een uur wordt de prijs berekend aan € 12,5 per kwartier + € 5 voor het remedieflesje.
Tijdens je proces heb je ook de mogelijkheid om enkel een remedieflesje aan te vragen met dezelfde samenstelling die werd bepaald in het vorige consult voor € 5.

Gesprekstherapie zonder de ondersteuning van Bach Bloesems is zeker ook mogelijk. Het consult duurt ongeveer één uur. Ook hier wordt de prijs berekend aan €12,5 per kwartier.

Een sessie lichaamsgerichte therapie of relaxatie duurt minimum 1 uur en kost € 50.
Langere sessies zijn mogelijk en worden verrekend aan € 25 per half uur.

Hoe verloopt een [sessie Bach Bloesem Remedies](./bachbloesemsessie.html)?  
Hoe verloopt een [sessie Lichaamsgerichte Therapie](./lichaamsgericht.html)?  
Hoe verloopt een [sessie Relaxatie](./relaxatie.html)?

Bij annulering van de afspraak minder dan 24u op voorhand of het onaangekondigd niet verschijnen op een afspraak zie ik me genoodzaakt 25 euro aan te rekenen.

n-zicht is gesitueerd in een rustige omgeving op [wandelafstand van het station Brugge](./map.html).