---
title: "Getuigenissen"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---


</br> 

"Warme ondersteuning en de kunst van niet oordelend luisteren... konden mij snel uit een korte depressie halen... dank daarvoor!" D.

<center>***</center>

</br>


"Bach bloesems zijn voor mij een zegen. Ik voel me er mentaal sterker door en bijgevolg ook gelukkiger. Natuurlijk zijn de begeleidende consulten van Fien hierbij cruciaal. Vanuit heel rake, juiste vragen en een heel puur inlevingsvermogen ontspint zich een gesprek dat zo deugdzaam is. De gesprekken leiden tot nieuwe inzichten. Op basis van deze consulten wordt dan in samenspraak een combinatie van bloesems samengesteld die op dat moment voor jou heel waardevol en ondersteunend is. Soms kan een bloesem verbazend sterk op je inwerken, dat heb ik al meermaals ondervonden! Dat kan best heel confronterend zijn. Maar soms moet je eens door een zure appel heen. Ook goed om weten en geruststellend is dat bijsturen of een extra consult kan op elk moment. Bachbloesemtherapie bij Fien is voor mij de beste vorm van ondersteuning in mijn persoonlijke groei waar ik intens dankbaar voor ben." Ilse, 52 jaar.

<center>***</center>

</br>

"Fien straalt een warme rust uit die me tot mezelf terugbrengt, iets waar ik haar heel dankbaar voor ben. Ik heb me steeds comfortabel gevoeld om mijn kwetsbaarheden te tonen en me breekbaar op te stellen.

De behandeling start met een gesprek dat mij steeds heel erg oplucht omdat ik telkens opnieuw merk dat Fien oprecht kan in-voelen wat ik onder woorden probeer te brengen. Een gesprek waarbij weinig woorden nodig zijn om me echt begrepen te voelen. Het geeft telkens een grote innerlijke rust.  Na het gesprek krijg ik een deugddoende massage waar ik echt kan van genieten omdat het eventjes heel rustig is in mijn hoofd.

Fien geeft me ook de vrijheid om zoveel tijd tussen behandelingen te laten als ik zelf verkies. Periodes waarin ik me even laat meesleuren door de drukke beslommeringen van mijn leven en niet genoeg tijd neem voor mezelf, kunnen op evenveel begrip rekenen als de momenten waarop ik haar terug contacteer voor een nieuwe sessie.

De naam n-zicht vind ik zeer treffend gekozen, Fien doorziet de meerlagigheid van een verhaal, van een gevoel, van het onzegbare.  Ze is geboren om te doen wat ze nu doet." Melanie (°1981)

<center>***</center>

 
