---
title: "n-zicht via Biodanza, Bach Bloesem Remedies en Lichaamsgerichte Therapie"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---


Hoe we ons voelen in het hier en nu bepaalt ons zijn en hoe we staan in onze omgeving. Luisteren naar ons lichaam laat ons toe bewust te worden van onze gevoelens en emoties en ze te erkennen. n-zicht heeft als missie om je op jouw tempo via Biodanza en therapie aan te laten komen bij je ware zijn, je "zelf" te versterken, je te ondersteunen in moeilijke momenten, je uit te nodigen om te durven verbinden en om het leven te vieren.

</br> 

<center>
**Biodanza**
</center>

</br> 

Tijdens [Biodanza](https://biodanzabrugge.be) word je uitgenodigd om je te durven verbinden met jezelf, de anderen en het universum. Waarbij je zonder aangeleerde pasjes vrij zal kunnen en durven bewegen. Letterlijk en figuurlijk. Het groepsgebeuren geeft je de kans om via contact met de anderen aan te komen bij jezelf. De ander is hierbij als het ware een spiegel. Dat wordt op een hele veilige manier opgebouwd vanuit een grote positiviteit. Hierbij vertrekken we vanuit het systeem [Biodanza](https://biodanzabrugge.be/) dat gebruik maakt van de kracht van muziek, dans en beweging in groep om tot een beleving (vivencia) te komen. Het plezier van bewegen, en, jezelf en de ander ontmoeten staan in Biodanza centraal. Individueel en in contact met anderen en dat heel trouw aan wie je werkelijk bent.

</br> 

<center>
**Therapeutisch werk** 
</center>

</br> 

Iedereen heeft op zijn weg wel eens periodes van stress, depressie, angst, onzekerheid, verdriet, lusteloosheid, kwaadheid, piekeren, overbezorgdheid, ... Emoties die je uit balans kunnen brengen en tot fysieke klachten kunnen leiden wanneer ze lang aanhouden.

Gemoedstoestanden vormen bij n-zicht het startpunt. Jij krijgt de mogelijkheid om je te focussen op je eigen behoeften waardoor je je gemoedstoestanden erkent, inzicht krijgt in emotionele processen en moeilijkheden in perspectief kan zetten.

Jij bepaalt waar je het over wil hebben. Het is jouw proces, jouw beweging om actief op weg te gaan en we volgen hierbij jouw ritme.

In een veilige en rustige omgeving help ik, [Fien Morel](./about.html), jou tot zelfkennis te komen d.m.v. gesprekstherapie op basis van [Bach Bloesem Remedies](./bachbloesems.html) en [Lichaamsgerichte Therapie](lichaamsgericht.html). Met veel warmte, positiviteit, begrip, respect en de nodige dosis humor zorg ik vanop de zijlijn voor de juiste steun en condities.

De therapieën ondersteunen het herstel van het emotioneel evenwicht en je persoonlijke groei en bewustwording. Tijdens een verkennend gesprek bekijken we wat je hulpvraag is en bij welke vorm je je het best voelt. Een combinatie van de verschillende therapieeën is zeker mogelijk. Uiteraard kan je bij n-zicht ook terecht voor een [ontspanningsmassage en relaxatie](./relaxatie.html).

- [Waarvoor kan je bij n-zicht terecht](./voorwie.html)
- [Wekelijkse Biodanza Groepen](https://biodanzabrugge.be/activiteiten.html)
