---
title: "Lichaamsgerichte Therapie"
output:
    html_document:
        code_download: false
        toc: false
        number_sections: false
        code_folding: "none"
---

In lichaamsgerichte therapie richten we de aandacht op het eigen lichaam, op lichamelijke sensaties en op lichamelijke functies zoals ademhaling, spierspanning en -ontspanning in relatie tot houding, stem, beweging, evenwicht, energie, kracht en ons midden. Het maakt ons bewuster van onszelf, onze emoties, beweging en gedrag en het stimuleert speelsheid, motivatie en creativiteit.  

Je leren ontspannen, het ontwikkelen van lichaamsbesef, lichaamsbewustzijn en lichaamsbelevingen zijn belangrijk voor het algemene lichamelijk en psychisch welzijn.

Lichaamsgerichte therapie kan ook zinvol zijn voor het ontwikkelen van een positiever zelfbeeld, van zelfvertrouwen, van een meer assertieve houding en voor het leren aangeven van grenzen. Het kan ondersteuning bieden in het erkennen, delen en verwerken van emoties, gevoelens en (traumatische) ervaringen.

